package socketserver;

public enum SmartMeterDataEnum {

	METER_ID,
	DATE_TIME,
	KILO_WATT_HOURS,
	KILO_WATT_TOTAL,
	KILO_WATT_AMPS_TOTAL, 
	KILO_VOLT_AMP_REACTIVE_TOTAL,
	PHASE_1_CURRENT,
	PHASE_1_VOLTAGE,
	PHASE_2_CURRENT,
	PHASE_2_VOLTAGE,
	PHASE_3_CURRENT,
	PHASE_3_VOLTAGE,
	POWER_FACTOR
}
